### ISSUE TITLE
TODO: Rewrite to skip unsupported devices

### ISSUE THREAD

**Issue by Bluebie** [Bluebie/homebridge-miio#3]
- [x] Rewrite addAccessory to create miio device and check `device.type == 'switch'` before adding to homekit
- [x] Write something to clear out existing unsupported devices, for existing users
- [x] Change architecture to add accessory to hoembridge only after it has been fully investigated and confirmed compatible
